name: CI
on:
  push:
    branches:
      - "main"
  pull_request:

# Only run on the latest ref
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Install Linux dependencies
        if: inputs.platform == 'linux'
        run: |
          sudo apt-get -y update
          sudo apt-get -y install make cmake
          sudo snap install zig --classic --beta
      - name: Install cargo zig-build
        run: |
          cargo install cargo-zigbuild
      - name: Build
        run: |
          ./build.sh
